apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-chart.fullname" . }}
  labels:
    {{- include "gateway-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "gateway-chart.fullname" . }}-secret
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gateway-chart.fullname" . }}-secret
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "gateway-chart.fullname" . }}-secret
                  key: dbName
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "gateway-chart.fullname" . }}-secret
                  key: jwtSecret
            - name: JWT_EXPIRATION_MS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gateway-chart.fullname" . }}-config
                  key: jwtExpirationTime
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
