apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-chart.fullname" . }}-secret
type: Opaque
data:
  dbUsername: {{.Values.h2.username|b64enc}}
  dbPassword: {{.Values.h2.password|b64enc}}
  dbName: {{.Values.h2.dbName|b64enc}}
  jwtSecret: {{.Values.jwt.secret|b64enc}}